-- NWB-M5 — Estrutura inicial do banco New Wave Barber
-- Criar projeto no Supabase e rodar esta migration antes do seed.

create type public.user_type as enum ('ADMIN', 'BARBEIRO', 'CLIENTE');
create type public.barber_type as enum ('INTERNO', 'FREELANCER');
create type public.chair_status as enum ('LIVRE', 'OCUPADA', 'MANUTENCAO');
create type public.appointment_status as enum ('PENDENTE', 'CONFIRMADO', 'EM_ATENDIMENTO', 'FINALIZADO', 'CANCELADO');
create type public.payment_method as enum ('PIX', 'DINHEIRO', 'CREDITO', 'DEBITO');

create table public.empresa (
  id bigint generated by default as identity primary key,
  nome text not null,
  slug text not null unique,
  logo text,
  telefone text,
  whatsapp text,
  instagram text,
  facebook text,
  tiktok text,
  endereco text,
  ativo boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.usuario (
  id bigint generated by default as identity primary key,
  empresa_id bigint references public.empresa(id) not null,
  nome text not null,
  email text not null,
  senha_hash text not null,
  tipo public.user_type not null,
  ativo boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.barbeiro (
  id bigint generated by default as identity primary key,
  empresa_id bigint references public.empresa(id) not null,
  usuario_id bigint references public.usuario(id),
  nome text not null,
  foto text,
  tipo public.barber_type not null,
  especialidade text,
  comissao numeric(5,2),
  ativo boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.cadeira (
  id bigint generated by default as identity primary key,
  empresa_id bigint references public.empresa(id) not null,
  numero text not null,
  status public.chair_status default 'LIVRE' not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.servico (
  id bigint generated by default as identity primary key,
  empresa_id bigint references public.empresa(id) not null,
  nome text not null,
  descricao text,
  duracao_minutos integer not null,
  valor numeric(10,2) not null,
  ativo boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.cliente (
  id bigint generated by default as identity primary key,
  empresa_id bigint references public.empresa(id) not null,
  nome text not null,
  telefone text not null,
  email text,
  data_nascimento date,
  observacao text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.agendamento (
  id bigint generated by default as identity primary key,
  empresa_id bigint references public.empresa(id) not null,
  cliente_id bigint references public.cliente(id) not null,
  barbeiro_id bigint references public.barbeiro(id) not null,
  servico_id bigint references public.servico(id) not null,
  cadeira_id bigint references public.cadeira(id),
  data date not null,
  hora_inicio time without time zone not null,
  hora_fim time without time zone not null,
  status public.appointment_status default 'PENDENTE' not null,
  forma_pagamento public.payment_method,
  observacao text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.usuario enable row level security;
alter table public.empresa enable row level security;
alter table public.barbeiro enable row level security;
alter table public.cadeira enable row level security;
alter table public.servico enable row level security;
alter table public.cliente enable row level security;
alter table public.agendamento enable row level security;
